version: '3'

services:
  portal-front:
    container_name: portal-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8080"